import requests
import datetime as dt
import smtplib
from email.message import EmailMessage
import os

MY_LAT = 48.837009 # Your latitude
MY_LONG = 2.630090 # Your longitude

response = requests.get(url="http://api.open-notify.org/iss-now.json")
response.raise_for_status()
data = response.json()

iss_latitude = float(data["iss_position"]["latitude"])
iss_longitude = float(data["iss_position"]["longitude"])

#Your position is within +5 or -5 degrees of the ISS position.
def check_position():
    return abs(MY_LAT - iss_latitude) <= 5 and abs(MY_LONG - iss_longitude) <= 5

parameters = {
    "lat": MY_LAT,
    "lng": MY_LONG,
    "formatted": 0,
    "tzid": "Europe/Paris",
}

response = requests.get("https://api.sunrise-sunset.org/json", params=parameters)
response.raise_for_status()
data = response.json()
sunrise = int(data["results"]["sunrise"].split("T")[1].split(":")[0])
sunset = int(data["results"]["sunset"].split("T")[1].split(":")[0])

time_now = dt.datetime.now()
# print(time_now.second)

#If the ISS is close to my current position
# and it is currently dark
# Then send me an email to tell me to look up.
# BONUS: run the code every 60 seconds.

# One-time account generated by Ethereal
ethereal_email = os.environ.get("EMAIL")
ethereal_password = os.environ.get("PASSWORD")
ethereal_host = os.environ.get("HOST")
ethereal_sender = os.environ.get("SENDER")

time_later = dt.datetime.now()
diff = time_later - time_now
# print(diff)

while 1:
    time_later = dt.datetime.now()
    diff = time_later - time_now
    if time_now.hour > 20 and diff >= dt.timedelta(seconds=5):
        print("60s passed")
        time_now = dt.datetime.now()
        with smtplib.SMTP(ethereal_host, 587) as connection:
            connection.starttls()
            connection.login(ethereal_email, ethereal_password)

            msg = EmailMessage()
            msg["From"] = ethereal_email
            msg["To"] = "abc@gmail.com" # Not important here because Inbound Email disabled
            msg["Subject"] = "Overhead Notifier"
            msg.set_content("The ISS is nearby")
            connection.send_message(msg)