##################### Extra Hard Starting Project ######################

# 1. Update the birthdays.csv

# 2. Check if today matches a birthday in the birthdays.csv

# 3. If step 2 is true, pick a random letter from letter templates and replace the [NAME] with the person's actual name from birthdays.csv

# 4. Send the letter generated in step 3 to that person's email address.

import smtplib
from email.message import EmailMessage
import datetime as dt

import pandas as pd
import os, re
import random
from dotenv import load_dotenv, find_dotenv

# Folder contains letter templates
template_folder = os.listdir("letter_templates")

# Open birthdays.csv file
try:
    df = pd.read_csv('birthdays.csv')
    # print(df.to_dict("index"))
    birthday_dict = df.to_dict("index")
except FileNotFoundError:
    birthday_dict = {}
    print("File not found")

# Get today month and day
now = dt.datetime.now()
today_month = now.month
today_day = now.day

# Find person who has birthday today
# print(birthday_dict)
email_list = []
matches = []
if birthday_dict:
    # Find all matched person and put them in a list
    matches = [person for person in birthday_dict.values() if person["month"]==today_month and person["day"]==today_day]
    # print(matches)

    # Get all template letters in folder and put them in a list
    if matches:
        files = [f for f in template_folder if re.match(r'^letter_\d+\.txt$', f)]
        # print(files)
        if files:
            for match in matches:
                with open(f'letter_templates/{random.choice(files)}', 'r') as selected_template:
                    # print(selected_template.readlines())
                    template_content = selected_template.read()
                    email_content = template_content.replace("[NAME]",match["name"])
                    receiver_email = match["email"]
                    email_list.append({
                        "email": receiver_email,
                        "message": email_content
                    })
        else:
            print("No email template available")
    else:
        print("No bỉrthday dât in birthdays.csv")

# Send email
# find .env automagically by walking up directories until it's found
dotenv_path = find_dotenv()

# load up the entries as environment variables
load_dotenv(dotenv_path)

# One-time account generated by Ethereal
ethereal_email = os.environ.get("EMAIL")
ethereal_password = os.environ.get("PASSWORD")
ethereal_host = "smtp.ethereal.email"
ethereal_sender = "Duane Huel"

# print(email_list)
# Change 22 to the time you wanna send email.
if now.hour == 22:
    with smtplib.SMTP(ethereal_host, 587) as connection:
        connection.starttls()
        connection.login(ethereal_email, ethereal_password)

        # Email messages can only have one "To:" header.
        # Each loop creates a fresh email to avoid having 2 headers in the same message
        for mail in email_list:
            msg = EmailMessage()
            msg["From"] = ethereal_email
            msg["To"] = mail["email"]
            msg["Subject"] = "Happy Birthday"
            msg.set_content(mail["message"])
            connection.send_message(msg)
