# import smtplib
# from email.message import EmailMessage
#
# gmail = ""
# yahoo_email = ""
# password_gmail = ""
# password_yahoo = ""
# yahoo_mail_host = "smtp.mail.yahoo.com"
# gmail_host = "smtp.gmail.com"
#
# msg = EmailMessage()
# msg["Subject"] = "TestPython"
# msg["From"] = yahoo_email
# msg["To"] = ""
# msg.set_content("Test python code")
#
# with smtplib.SMTP(host=yahoo_mail_host, port=587) as connection:
#     connection.ehlo()
#     connection.starttls()
#     connection.ehlo()
#     connection.login(user=yahoo_email, password=password_yahoo)
#     connection.send_message(msg)

# Using https://ethereal.email/

# import smtplib
# from email.message import EmailMessage
#
# # One-time account generated by Ethereal,
# ethereal_email = "teresa.hills47@ethereal.email"
# ethereal_password = "YTeKVYpuVjtnEcEXfs"
# ethereal_host = "smtp.ethereal.email"
#
# msg = EmailMessage()
# msg["Subject"] = "TestPython"
# msg["From"] = ethereal_email
# msg["To"] = "test@gmail.com"
# # Remember that if sending messages through SMTP then no message is actually delivered,
# # all messages are caught and you can see these in the Messages page or by using your favorite IMAP/POP3 client.
# msg.set_content("Test python code")
#
# with smtplib.SMTP(host=ethereal_host, port=587) as connection:
#     connection.ehlo()
#     connection.starttls()
#     connection.ehlo()
#     connection.login(user=ethereal_email, password=ethereal_password)
#     connection.send_message(msg)

# Message received via: https://ethereal.email/messages

# import datetime as dt
#
# now = dt.datetime.now()
# year = now.year
# month = now.month
# day_of_week = now.weekday()
# print(year)
# print(now)
#
# date_of_birth = dt.datetime(year= 1995, month=3, day=13)
# print(date_of_birth)

import smtplib
from email.message import EmailMessage
import datetime as dt
import pandas as pd
import random

# One-time account generated by Ethereal,
ethereal_email = "teresa.hills47@ethereal.email"
ethereal_password = "YTeKVYpuVjtnEcEXfs"
ethereal_host = "smtp.ethereal.email"

# msg = EmailMessage()
# msg["Subject"] = "Weekly Quote"
# msg["From"] = ethereal_email
# Remember that if sending messages through SMTP then no message is actually delivered,
# all messages are caught and you can see these in the Messages page or by using your favorite IMAP/POP3 client.
# Receiver is not important here
# msg["To"] = "test@gmail.com"
# Message received via: https://ethereal.email/messages
# msg.set_content("Test python code")

try:
    df = pd.read_csv('quotes.txt', header=None)
    data_list = df[0].to_list()
except FileNotFoundError:
    data_list = []
    print("File not found")

# Simpler read file solution
# with open("quotes.txt") as quote_file:
#     all_quotes = quote_file.readlines()
#     quote = random.choice(all_quotes)

now = dt.datetime.now()
day_of_week = now.weekday()
# Weekday is 6 for testing, since code is developed on sunday
# Replace by 0 for monday
if day_of_week == 6:
    random_quote = random.choice(data_list)
    print(random_quote)
    # msg.set_content(random_quote)
    with smtplib.SMTP(host=ethereal_host, port=587) as connection:
        connection.starttls()
        connection.login(user=ethereal_email, password=ethereal_password)
        # connection.send_message(msg)
        # ehlo() isn’t used because smtplib already calls it automatically
        connection.sendmail(
            from_addr= ethereal_email,
            to_addrs= ethereal_email,
            msg= f"Subject:Weekly Quote\n\n{random_quote}"
        )
